# .bashrc

# Set prompt
export PS1="\[\e[36m\]\w\[\e[m\]\\$ "

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

alias ls="ls --color"
